apiVersion: v1
data:
  # Please follow instruction in document to generate new SSL certs
  tls.key: /home/tharshini9099/aqua_enforcer.key
  tls.crt: /home/tharshini9099/aqua_enforcer.crt
kind: Secret
metadata:
  annotations:
    description: Aqua LB SSL certificates to communicate with external enforcers using TLS
  labels:
    deployedby: aqua-yaml
  name: aqua-lb-certs
  namespace: aqua
type: Opaque
